name: flutter3_desktop_app
description: "flutter3_desktop_app package."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter3_desktop_core:
    path: ../flutter3_desktop_core
  flutter3_app:
    path: ../../Flutter3Core/flutter3_app

  # https://pub.dev/packages/super_context_menu
  # https://pub.dev/packages/collection
  # https://pub.dev/packages/device_info_plus
  # https://pub.dev/packages/pixel_snap
  # https://pub.dev/packages/super_native_extensions
  super_context_menu: ^0.8.24
  # https://pub.dev/packages/pixel_snap
  pixel_snap: ^0.1.5

dependency_overrides:
  # Because every version of flutter3_desktop_app from path depends on flutter3_app from path which depends on device_info_plus ^11.1.1, every version of flutter3_desktop_app from path requires device_info_plus ^11.1.1.
  device_info_plus: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
